name: Test compilation & tests

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-24.04, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Build hello
        run: make all
      
      - name: Build hello-napi
        working-directory: hello-napi
        run: npm run install

      - name: Run tests
        working-directory: hello-napi
        run: npm run test
