name: Test compilation & tests

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            cmake_configure: configure:win32
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Setup cmake
        uses: inhibitor1217/actions-setup-cmake@v2.1.2

      - name: Check CMake version
        run: cmake --version

      - name: Build hello
        run: make all
      
      - name: Build hello-napi
        working-directory: hello-napi
        run: |
          npm install
          npm run ${{ matrix.cmake_configure }}
          npm run compile

      - name: Run tests
        working-directory: hello-napi
        run: npm run test
